name: bollywood
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - scrapy=1.5.1
  - jupyter=1.0.0
  - pandas=0.23.4
  - bokeh=0.13.0
  - gensim=3.4.0
  - scikit-learn=0.19.1
  - matplotlib=2.2.3
